# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d187845b6de28c44a14c82fd365707270e09cc47cd3707b402293e112346afe47be7e771658d9d8247cff191f20bc52f7afbca8f566c9ee3e3d94a2bb280d164

test:
  secret_key_base: c59054854b08166be31d446698e77bb640d4dfbf4bd9271fd5a774900748597591862a1d983633867ab190c844759003fa90db14eb163a115455c9e1f75a8dc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
